name: FAMASenv
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - ncurses=6.5
  - numpy=2.3.3
  - openssl=3.5.3
  - pandas=2.3.2
  - pip=25.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.2
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
